development: &default
  adapter: postgresql
  database: pullfeed_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: pullfeed_test

production:
  <<: *default
  database: pullfeed_production
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

staging:
  <<: *default
  database: pullfeed_staging
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
