development: &default
  adapter: postgresql
  database: pr-rss_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: pr-rss_test

production:
  <<: *default
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PULLFEED_DB_PASS'] %>
